# https://github.com/actions/labeler

github_actions:
  changed-files:
    - '.github/**'

dictionaries:
  any-glob-to-any-file:
    - '.dictionaries/**'
    - '.cspell.json'

cmake:
  any-glob-to-any-file:
    - 'cmake/**/*.cmake'
    - '**/CMakeLists.txt'
    - 'CMakePresets.json'
    - 'conanfile.py'

python:
  changed-files:
    - '**/*.py'
    - '**/*.py.in'
    - 'requirements.txt'
    - 'py_requirements.txt'
    - '!conanfile.py'

doc:
  changed-files:
    - 'doc/**'
    - 'doc_ng/**'
    - '**/*.{md,rst,txt}'
    - '**/doxyfile.in'
    - '**/*.dot'
    - '!**/CMakeLists.txt'
    - '!requirements.txt'
    - '!py_requirements.txt'

l10n:
  changed-files:
    - 'l10n/**'
    - '!**/CMakeLists.txt'

source:
  changed-files:
    - 'source/**'
    - '!**/CMakeLists.txt'

testsuite:
  changed-files:
    - 'testsuite/**'
    - '!**/CMakeLists.txt'

# branch related

feature-br:
 - head-branch: ['^feature', 'feature']

update-br:
 - head-branch: ['^update', 'update', '^better', 'better']

fix-br:
 - head-branch: ['^fix', 'fix']

# Add 'release' label to any PR that is opened against the `main` branch
release:
 - base-branch: 'main'
