# https://github.com/actions/labeler

github_actions:
- changed-files:
  - any-glob-to-any-file:
    - '.github/**'

dictionaries:
- changed-files:
  - any-glob-to-any-file:
    - '.dictionaries/**'
    - '.cspell.json'

cmake:
- changed-files:
  - any-glob-to-any-file:
    - 'cmake/**/*.cmake'
    - '**/CMakeLists.txt'
    - 'CMakePresets.json'
    - 'conanfile.py'

python:
- changed-files:
  - any-glob-to-any-file:
    - '**/*.py'
    - '**/*.py.in'
    - 'requirements.txt'
    - 'py_requirements.txt'
  - all-globs-to-all-files:
    - '!conanfile.py'

doc:
- changed-files:
  - any-glob-to-any-file:
    - 'doc/**'
    - 'doc_ng/**'
    - '**/*.{md,rst,txt}'
    - '**/doxyfile.in'
    - '**/*.dot'
  - all-globs-to-all-files:
    - '!**/CMakeLists.txt'

l10n:
- changed-files:
  - any-glob-to-any-file:
    - 'l10n/**'
  - all-globs-to-all-files:
    - '!**/CMakeLists.txt'

source:
- changed-files:
  - any-glob-to-any-file:
    - 'source/**'
  - all-globs-to-all-files:
    - '!**/CMakeLists.txt'

testsuite:
- changed-files:
  - any-glob-to-any-file:
    - 'testsuite/**'
  - all-globs-to-all-files:
    - '!**/CMakeLists.txt'

# branch related

feature:
 - head-branch: ['^feature', 'feature']

update:
 - head-branch: ['^update', 'update']

fix:
 - head-branch: ['^fix', 'fix']

# Add 'release' label to any PR that is opened against the `main` branch
release:
 - base-branch: 'main'
