# https://github.com/actions/labeler

github_actions:
- changed-files:
  - any-glob-to-any-file:
    - '.github/**'

dictionaries:
- changed-files:
  - any-glob-to-any-file:
    - '.dictionaries/**'
    - '.cspell.json'

cmake:
- changed-files:
  - any-glob-to-any-file:
    - 'cmake/**/*.cmake'
    - '**/CMakeLists.txt'
    - 'CMakePresets.json'
    - 'conanfile.py'

python:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.py'
      - '**/*.py.in'
      - 'requirements.txt'
      - 'py_requirements.txt'
    - all-globs-to-all-files:
      - '!conanfile.py'

doc:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - 'doc/**'
      - 'doc_ng/**'
      - '**/*.{md,rst,txt}'
      - '**/doxyfile.in'
      - '**/*.dot'
    - all-globs-to-all-files:
      - '!**/CMakeLists.txt'
      - '!requirements.txt'
      - '!py_requirements.txt'

l10n:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - 'l10n/**'
    - all-globs-to-all-files:
      - '!**/CMakeLists.txt'

source:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - 'source/**'
    - all-globs-to-all-files:
      - '!**/CMakeLists.txt'

testsuite:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - 'testsuite/**'
    - all-globs-to-all-files:
      - '!**/CMakeLists.txt'

# branch related

feature-br:
 - head-branch: ['^feature', 'feature']

update-br:
 - head-branch: ['^update', 'update', '^better', 'better']

fix-br:
 - head-branch: ['^fix', 'fix']

# Add 'release' label to any PR that is opened against the `main` branch
release:
 - base-branch: 'main'
