name: 'Clang tidy review'

on:
  [ pull_request ]

env:
  CONAN_V2_MODE : 1

jobs:
  review:
    runs-on: ubuntu-22.04

    steps:
    - name: Install basic dependencies
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends -y \
          cmake ninja-build ccache clang-14 clang-format clang-tidy

    - name: Install conan package manager
      run: |
        python -m pip install --upgrade pip
        pip --disable-pip-version-check --no-cache-dir install wheel conan

    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Setup Github's cache for conan
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-clang-conan-${{ hashFiles('conanfile.txt') }}
        path: |
          ~/.conan

    - name: Setup Github's cache for compiler cache
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-clang-ccache
        path: |
          ~/.config/ccache
          ~/.cache/ccache

    - name: CMake configuration
      run: |
        cmake --preset ci-linux-clang

    - name: Clang tidy review
      id: clang-tidy-review
      uses: ZedThree/clang-tidy-review@v0.16.0
      with:
        config_file: .clang-tidy
        cmake_command: cmake --preset ci-linux-clang

    - name: Passed C++ style guide checks?!
      if: steps.clang-tidy-review.outputs.total_comments > 0
      run: |
        echo "Some files failed the Clang tidy review!"

    - name: Clean up conan build & sources
      run: |
        conan remove -f "*" --builds
        conan remove -f "*" --src
