name: 'Clang tidy review'

on:
  [ pull_request ]

jobs:
  tidy-review:
    runs-on: ubuntu-24.04

    steps:

    - name: Trigger event
      run: |
        echo "Triggered by ${{ github.event_name }}"

    - name: Install basic dependencies
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends -y \
          cmake ninja-build clang clang-tools clang-tidy

    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set Github runner's env (CXX=clang++)
      run: |
        echo "CXX=clang++" >> "$GITHUB_ENV"
                
    - name: Install Conan package manager
      id: conan2
      run: |
        pip --disable-pip-version-check --no-cache-dir install wheel conan

    - name: Cache Conan2 dependencies
      id: conan2-cache
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-conan-${{ hashFiles('conanfile.py') }}
        path: |
          ~/.conan2

    #- name: Check the state of installed dependencies by Conan2
    #  if: ${{ steps.conan2-cache.outputs.cache-hit != 'true' }}
    #  run: |
    #    conan profile detect --force --name default

    #- name: CMake configuration
    #  run: |
    #    cmake --preset clang

    - name: Run Clang tidy review
      id: clang-tidy-review
      uses: ZedThree/clang-tidy-review@v0.20.1
      with:
        build_dir: ${{ github.workspace }}/build
        cmake_command: |
          conan profile detect --force --name default
          cmake --preset clang
        config_file: .clang-tidy

    - name: Uploads an artefact containing clang_fixes.json
      id: clang-tidy-upload-review
      uses: ZedThree/clang-tidy-review/upload@v0.20.1

    - name: Passed C++ style guide checks?!
      if: steps.clang-tidy-review.outputs.total_comments > 0
      run: |
        echo "Some files failed the Clang tidy review!"
